using YamlDotNet.Serialization;

namespace MITREModels.YAML;

public class AtomicTest
{
    [YamlMember(Alias = "name")]
    public string Name { get; set; }

    [YamlMember(Alias = "auto_generated_guid")]
    public Guid AutoGeneratedGuid { get; set; }

    [YamlMember(Alias = "description")]
    public string Description { get; set; }

    [YamlMember(Alias = "supported_platforms")]
    public List<string> SupportedPlatforms { get; set; }

    [YamlMember(Alias = "input_arguments")]
    public Dictionary<string, InputArgument> InputArguments { get; set; }

    [YamlMember(Alias = "dependency_executor_name")]
    public string DependencyExecutorName { get; set; }

    [YamlMember(Alias = "dependencies")]
    public List<Dependency> Dependencies { get; set; }

    [YamlMember(Alias = "executor")]
    public Executor Executor { get; set; }

    public Technique Technique { get; set; }
}